# Training Configuration

# Import default config
defaults:
  - default

# Training Parameters
training:
  # Optimization
  optimizer:
    name: "adam"
    lr: 0.001
    weight_decay: 1e-4
    
  # Learning Rate Schedule
  lr_scheduler:
    name: "cosine"
    warmup_steps: 1000
    max_steps: 100000
    
  # Training Loop
  num_epochs: 100
  batch_size: 2048
  grad_clip: 1.0
  
  # Self-Play
  self_play:
    num_games: 5000
    num_workers: 4
    max_queue_size: 10000
    min_buffer_size: 10000
    max_buffer_size: 500000
    
  # Evaluation
  eval:
    frequency: 1000  # 평가 주기 (학습 스텝)
    num_games: 100   # 평가 게임 수
    
  # Checkpointing
  checkpoint:
    frequency: 1000  # 저장 주기 (학습 스텝)
    keep_last: 5     # 유지할 최근 체크포인트 수
    
  # Early Stopping
  early_stopping:
    patience: 10     # 성능 향상 없을 때 기다리는 에폭 수
    min_delta: 0.01  # 최소 성능 향상 기준 